### ISSUE TITLE
Issue with lexactivator function's parameter passing

### ISSUE THREAD

**Issue by PiraisudanM** [cryptlex/lexactivator-go#1]
Currently, I'm working on cryptlex integration with Golang. When I'm trying to build the provided LexActivator sample from GitHub (https://github.com/cryptlex/lexactivator-go/tree/master/examples), getting the following error:
"cannot use _Cfunc_CString(" < Included product data here > ") (type *_Ctype_char) as type *_Ctype_ushort in argument to _Cfunc_SetProductData".

I have downloaded LexActivator for Windows 3.9.1(https://app.cryptlex.com/downloads) and copied "LexActivator.dll" and "LexActivator.lib" in the "libs" directory.

Installed Go version: 1.14

It looks like a typecasting issue while passing the parameter to the LexActivator function. How to resolve this issue?

**Comment by adnan-kamili** [comment]
Fixed.
