### ISSUE TITLE
Revoke or deletion of license key does not make IsProductGenuine return an error

### ISSUE THREAD

**Issue by jingkai1** [cryptlex/lexactivator-go#2]
[lisense.txt](https://github.com/cryptlex/lexactivator-go/files/5068665/lisense.txt)

**Comment by jingkai1** [comment]
when license.go is running , I delete this license. licenseCallback() get state is 59, but in UseLicense() , status is 0, not 1, this license.go is running activated. 

status 0
License expiry timestamp: 1597385648
2020-08-14 14:14:08
License is genuinely activated!
2020/08/13 14:18:45 License error status: 59
status 0
License expiry timestamp: 1597385648
2020-08-14 14:14:08
License is genuinely activated!
2020/08/13 14:19:44 License error status: 59

**Comment by jingkai1** [comment]
revoke also appear this question

**Comment by adnan-kamili** [comment]
Fixed.
